# Generated by Django 4.1.8 on 2023-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=13)),
                ('customerId', models.CharField(max_length=13)),
                ('balance', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
